### ISSUE TITLE
What's work status?

### ISSUE THREAD

**Issue by rngtng** [AlphaB/sidekiq_exporter#1]
Hey AlphaB!
Looks like we have the same problem/idea - I'm working on a sidekiq -> prometheus exporter too. What's you status, any code you can share?

**Comment by AlphaB** [comment]
Hi!
I have working prototype, but it's not ready for open source. 
And I can't say when I will have time to put it in order.

**Comment by rngtng** [comment]
ok thanks. too bad :(
